import { Router } from 'express';

import userRoutes from '../users';
import uploadRoutes from '../upload';
import creditRoutes from '../credit';
import agentRoutes from '../agents';
import agentProfileRoutes from '../agentProfile';
import locationRoutes from '../locationRoutes';
import geoFenceRoutes from '../geoFenceRoutes';
import agentLocationRoutes from '../agentLocationRoutes';
import aiRoutes from '../ai';
import aiExtractionRoutes from '../ai/extraction';
import merchantRoutes from '../merchants';
import offerRoutes from '../offers';
import jobPostingRoutes from '../job/jobPostingRoutes';
import recommendationRoutes from '../job/recommendationRoutes';
import consumerDemandRoutes from '../consumerDemand';
import reviewRoutes from '../reviews';
import transactionRoutes from '../transaction';
import authRoutes from '../auth';
import disclosureRoutes from '../disclosure';
import userPrivacyRoutes from '../userPrivacy';
import { strictAuthLimiter } from '../../middleware/rateLimiter';
import pointsRoutes from '../points';
import matchQueryRoutes from '../matchQuery';
import datingRoutes from '../dating';
import visionSharePublishRoutes from '../visionShare/publish';
import visionSharePaymentRoutes from '../visionShare/payment';
import reportRoutes from '../reports';
import moderationRoutes from '../moderation';
import moderationAnalyticsRoutes from '../moderationAnalytics';
import appealRoutes from '../appeals';
import sensitiveWordRoutes from '../sensitiveWords';

import healthRoutes from './health';
import sceneRoutes from './scene';
import chatRoutes from './chat';

const router: Router = Router();

// Mount routes
router.use('/health', healthRoutes);
router.use('/auth', strictAuthLimiter, authRoutes);
router.use('/scenes', sceneRoutes);
router.use('/disclosure', disclosureRoutes);
router.use('/users', userRoutes);
router.use('/users', userPrivacyRoutes);
router.use('/upload', uploadRoutes);
router.use('/credit', creditRoutes);
router.use('/points', pointsRoutes);
router.use('/agents', agentRoutes);
router.use('/agents', agentProfileRoutes);
router.use('/location', locationRoutes);
router.use('/location', agentLocationRoutes);
router.use('/geofences', geoFenceRoutes);
router.use('/ai', aiRoutes);
router.use('/ai', aiExtractionRoutes);
router.use('/merchants', merchantRoutes);
router.use('/offers', offerRoutes);
router.use('/jobs', jobPostingRoutes);
router.use('/jobs', recommendationRoutes);
router.use('/consumer', consumerDemandRoutes);
router.use('/reviews', reviewRoutes);
router.use('/chat', chatRoutes);
router.use('/matches', matchQueryRoutes);
router.use('/dating', datingRoutes);
router.use('/reports', reportRoutes);
router.use('/moderation', moderationRoutes);
router.use('/moderation/analytics', moderationAnalyticsRoutes);
router.use('/appeals', appealRoutes);
router.use('/sensitive-words', sensitiveWordRoutes);
router.use('/visionshare', visionSharePublishRoutes);
router.use('/visionshare/payment', visionSharePaymentRoutes);
router.use('/transactions', transactionRoutes);

export default router;
