import { SceneConfig, SceneMetadata, SceneFieldDefinition, SceneCapability, SceneSection } from '../../types/scene';

const metadata: SceneMetadata = {
  id: 'agentdate',
  name: 'Agent约会',
  nameEn: 'AgentDate',
  description: '寻找约会对象、建立社交连接的场景',
  icon: '💕',
  color: '#E91E63',
  version: '1.0.0',
  isActive: true,
  createdAt: new Date('2026-01-01'),
  updatedAt: new Date('2026-01-01'),
};

const fields: SceneFieldDefinition[] = [
  {
    id: 'dating_purpose',
    name: 'datingPurpose',
    label: '约会目的',
    type: 'select',
    required: true,
    options: [
      { value: 'serious_relationship', label: '认真交往', icon: '💍' },
      { value: 'casual_dating', label: '轻松约会', icon: '☕' },
      { value: 'friendship', label: '交友', icon: '🤝' },
      { value: 'marriage', label: '寻找结婚对象', icon: '💒' },
    ],
    ui: { order: 1, section: 'basic' },
  },
  {
    id: 'preferred_gender',
    name: 'preferredGender',
    label: '期望对象性别',
    type: 'select',
    required: true,
    options: [
      { value: 'male', label: '男性' },
      { value: 'female', label: '女性' },
      { value: 'any', label: '不限' },
    ],
    ui: { order: 2, section: 'basic' },
  },
  {
    id: 'age_range',
    name: 'ageRange',
    label: '期望年龄范围',
    type: 'range',
    required: true,
    ui: { order: 3, section: 'basic', placeholder: '选择年龄范围' },
  },
  {
    id: 'location_preference',
    name: 'locationPreference',
    label: '地点偏好',
    type: 'select',
    required: false,
    options: [
      { value: 'same_city', label: '同城', icon: '🏙️' },
      { value: 'nearby', label: '附近城市', icon: '🚗' },
      { value: 'any', label: '不限', icon: '🌍' },
    ],
    ui: { order: 4, section: 'basic' },
  },
  {
    id: 'interests',
    name: 'interests',
    label: '兴趣爱好',
    type: 'multiselect',
    required: false,
    options: [
      { value: 'movies', label: '电影', icon: '🎬' },
      { value: 'music', label: '音乐', icon: '🎵' },
      { value: 'sports', label: '运动', icon: '⚽' },
      { value: 'travel', label: '旅行', icon: '✈️' },
      { value: 'reading', label: '阅读', icon: '📚' },
      { value: 'gaming', label: '游戏', icon: '🎮' },
      { value: 'cooking', label: '烹饪', icon: '🍳' },
      { value: 'outdoor', label: '户外活动', icon: '🏔️' },
      { value: 'art', label: '艺术', icon: '🎨' },
      { value: 'tech', label: '科技', icon: '💻' },
    ],
    ui: { order: 5, section: 'personal', placeholder: '选择兴趣爱好' },
  },
  {
    id: 'personality_traits',
    name: 'personalityTraits',
    label: '性格特点',
    type: 'multiselect',
    required: false,
    options: [
      { value: 'outgoing', label: '外向' },
      { value: 'introverted', label: '内向' },
      { value: 'humorous', label: '幽默' },
      { value: 'serious', label: '严肃' },
      { value: 'romantic', label: '浪漫' },
      { value: 'practical', label: '务实' },
      { value: 'creative', label: '有创意' },
      { value: 'adventurous', label: '爱冒险' },
    ],
    ui: { order: 6, section: 'personal', placeholder: '选择性格标签' },
  },
  {
    id: 'lifestyle',
    name: 'lifestyle',
    label: '生活方式',
    type: 'select',
    required: false,
    options: [
      { value: 'early_bird', label: '早起型', icon: '🌅' },
      { value: 'night_owl', label: '夜猫子', icon: '🌙' },
      { value: 'active', label: '活跃', icon: '⚡' },
      { value: 'relaxed', label: '悠闲', icon: '😌' },
      { value: 'health_conscious', label: '注重健康', icon: '🥗' },
    ],
    ui: { order: 7, section: 'personal' },
  },
  {
    id: 'occupation',
    name: 'occupation',
    label: '职业',
    type: 'text',
    required: false,
    ui: { order: 8, section: 'background', placeholder: '你的职业' },
  },
  {
    id: 'education',
    name: 'education',
    label: '教育背景',
    type: 'select',
    required: false,
    options: [
      { value: 'high_school', label: '高中' },
      { value: 'college', label: '大专' },
      { value: 'bachelor', label: '本科' },
      { value: 'master', label: '硕士' },
      { value: 'phd', label: '博士' },
    ],
    ui: { order: 9, section: 'background' },
  },
  {
    id: 'looking_for',
    name: 'lookingFor',
    label: '寻找什么样的TA',
    type: 'textarea',
    required: false,
    validation: [
      { type: 'minLength', value: 20, message: '至少输入20个字符' },
      { type: 'maxLength', value: 500, message: '最多500个字符' },
    ],
    ui: {
      order: 10,
      section: 'about',
      placeholder: '描述你理想的约会对象...',
      helpText: '让TA了解你在寻找什么样的人',
    },
  },
  {
    id: 'about_me',
    name: 'aboutMe',
    label: '关于我',
    type: 'textarea',
    required: true,
    validation: [
      { type: 'minLength', value: 30, message: '至少输入30个字符' },
      { type: 'maxLength', value: 1000, message: '最多1000个字符' },
    ],
    ui: {
      order: 11,
      section: 'about',
      placeholder: '介绍一下自己...',
      helpText: '这是最重要的部分，请详细描述',
    },
  },
  {
    id: 'deal_breakers',
    name: 'dealBreakers',
    label: '不可接受的事',
    type: 'multiselect',
    required: false,
    options: [
      { value: 'smoking', label: '吸烟' },
      { value: 'drinking', label: '酗酒' },
      { value: 'lying', label: '撒谎' },
      { value: 'disrespect', label: '不尊重他人' },
      { value: 'unambitious', label: '没有上进心' },
    ],
    ui: { order: 12, section: 'preferences', placeholder: '选择你的底线' },
  },
];

const capabilities: SceneCapability[] = [
  {
    id: 'photo_verification',
    name: '照片验证',
    description: '通过视频验证确保照片真实性',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
  },
  {
    id: 'video_profile',
    name: '视频简介',
    description: '上传视频介绍自己',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
  },
  {
    id: 'ice_breakers',
    name: '破冰话题',
    description: '智能推荐开场话题',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
  },
  {
    id: 'date_planning',
    name: '约会规划',
    description: '帮助规划第一次约会',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
  },
  {
    id: 'safety_check',
    name: '安全检查',
    description: '约会前安全提醒和检查',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
  },
  {
    id: 'compatibility_score',
    name: '匹配度评分',
    description: '基于资料计算匹配度',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
  },
];

const sections: SceneSection[] = [
  {
    id: 'basic',
    title: '基本信息',
    icon: '📋',
    order: 1,
    fields: ['dating_purpose', 'preferred_gender', 'age_range', 'location_preference'],
  },
  {
    id: 'personal',
    title: '个人特质',
    icon: '✨',
    order: 2,
    fields: ['interests', 'personality_traits', 'lifestyle'],
  },
  {
    id: 'background',
    title: '背景信息',
    icon: '🎓',
    order: 3,
    fields: ['occupation', 'education'],
  },
  {
    id: 'about',
    title: '关于你',
    icon: '💬',
    order: 4,
    fields: ['looking_for', 'about_me'],
  },
  {
    id: 'preferences',
    title: '偏好设置',
    icon: '⚙️',
    order: 5,
    fields: ['deal_breakers'],
  },
];

export const agentDateConfig: SceneConfig = {
  id: 'agentdate',
  metadata,
  fields,
  capabilities,
  templates: [
    {
      id: 'serious_dater',
      name: '认真交往',
      description: '寻找长期关系的模板',
      isPreset: true,
      isDefault: false,
      fieldValues: {
        datingPurpose: 'serious_relationship',
        lifestyle: 'health_conscious',
      },
    },
    {
      id: 'casual_dater',
      name: '轻松约会',
      description: '轻松交友的模板',
      isPreset: true,
      isDefault: true,
      fieldValues: {
        datingPurpose: 'casual_dating',
        interests: ['movies', 'music', 'travel'],
      },
    },
  ],
  validation: {
    rules: [],
    preventSubmitOnError: true,
    showWarnings: true,
  },
  ui: {
    sections,
    layout: 'tabs',
    theme: {
      primaryColor: '#E91E63',
      secondaryColor: '#F8BBD9',
      backgroundColor: '#FCE4EC',
      textColor: '#333333',
    },
  },
};

export default agentDateConfig;
