import { SceneConfig, SceneMetadata, SceneFieldDefinition, SceneCapability, SceneSection } from '../../types/scene';

const metadata: SceneMetadata = {
  id: 'agentjob',
  name: 'Agent求职',
  nameEn: 'AgentJob',
  description: '求职招聘、展示职业能力的场景',
  icon: '💼',
  color: '#2196F3',
  version: '1.0.0',
  isActive: true,
  createdAt: new Date('2026-01-01'),
  updatedAt: new Date('2026-01-01'),
};

const fields: SceneFieldDefinition[] = [
  {
    id: 'job_type',
    name: 'jobType',
    label: '求职类型',
    type: 'select',
    required: true,
    options: [
      { value: 'full_time', label: '全职', icon: '💼' },
      { value: 'part_time', label: '兼职', icon: '⏰' },
      { value: 'contract', label: '合同', icon: '📄' },
      { value: 'freelance', label: '自由职业', icon: '🏠' },
      { value: 'internship', label: '实习', icon: '🎓' },
    ],
    ui: { order: 1, section: 'basic' },
  },
  {
    id: 'job_category',
    name: 'jobCategory',
    label: '职位类别',
    type: 'select',
    required: true,
    options: [
      { value: 'tech', label: '技术', icon: '💻' },
      { value: 'design', label: '设计', icon: '🎨' },
      { value: 'marketing', label: '市场', icon: '📢' },
      { value: 'sales', label: '销售', icon: '💰' },
      { value: 'operations', label: '运营', icon: '⚙️' },
      { value: 'finance', label: '财务', icon: '💹' },
      { value: 'hr', label: '人力资源', icon: '👥' },
      { value: 'product', label: '产品', icon: '📱' },
    ],
    ui: { order: 2, section: 'basic' },
  },
  {
    id: 'target_positions',
    name: 'targetPositions',
    label: '目标职位',
    type: 'tags',
    required: true,
    ui: { order: 3, section: 'basic', placeholder: '如：前端工程师、产品经理' },
  },
  {
    id: 'expected_salary',
    name: 'expectedSalary',
    label: '期望薪资',
    type: 'range',
    required: false,
    options: [
      { value: '0-5k', label: '5K以下' },
      { value: '5k-10k', label: '5K-10K' },
      { value: '10k-20k', label: '10K-20K' },
      { value: '20k-30k', label: '20K-30K' },
      { value: '30k-50k', label: '30K-50K' },
      { value: '50k+', label: '50K以上' },
    ],
    ui: { order: 4, section: 'basic' },
  },
  {
    id: 'work_location',
    name: 'workLocation',
    label: '工作地点',
    type: 'select',
    required: false,
    options: [
      { value: 'remote', label: '远程', icon: '🏠' },
      { value: 'hybrid', label: '混合', icon: '🔄' },
      { value: 'onsite', label: '现场', icon: '🏢' },
    ],
    ui: { order: 5, section: 'basic' },
  },
  {
    id: 'work_experience',
    name: 'workExperience',
    label: '工作经验',
    type: 'select',
    required: true,
    options: [
      { value: 'entry', label: '应届生', icon: '🌱' },
      { value: 'junior', label: '1-3年', icon: '🌿' },
      { value: 'mid', label: '3-5年', icon: '🌲' },
      { value: 'senior', label: '5-10年', icon: '🌳' },
      { value: 'expert', label: '10年以上', icon: '⭐' },
    ],
    ui: { order: 6, section: 'experience' },
  },
  {
    id: 'skills',
    name: 'skills',
    label: '技能',
    type: 'tags',
    required: true,
    ui: {
      order: 7,
      section: 'experience',
      placeholder: '如：React, Node.js, Python',
      helpText: '添加你的专业技能',
    },
  },
  {
    id: 'certifications',
    name: 'certifications',
    label: '证书',
    type: 'multiselect',
    required: false,
    options: [
      { value: 'pmp', label: 'PMP' },
      { value: 'aws', label: 'AWS认证' },
      { value: 'google', label: 'Google认证' },
      { value: 'azure', label: 'Azure认证' },
      { value: 'cfa', label: 'CFA' },
      { value: 'cpa', label: 'CPA' },
    ],
    ui: { order: 8, section: 'experience', placeholder: '选择相关证书' },
  },
  {
    id: 'education',
    name: 'education',
    label: '学历',
    type: 'select',
    required: false,
    options: [
      { value: 'high_school', label: '高中' },
      { value: 'associate', label: '大专' },
      { value: 'bachelor', label: '本科' },
      { value: 'master', label: '硕士' },
      { value: 'phd', label: '博士' },
    ],
    ui: { order: 9, section: 'experience' },
  },
  {
    id: 'portfolio_url',
    name: 'portfolioUrl',
    label: '作品集/简历链接',
    type: 'url',
    required: false,
    ui: { order: 10, section: 'experience', placeholder: 'https://...' },
  },
  {
    id: 'career_summary',
    name: 'careerSummary',
    label: '职业概述',
    type: 'textarea',
    required: true,
    validation: [
      { type: 'minLength', value: 50, message: '至少输入50个字符' },
      { type: 'maxLength', value: 1000, message: '最多1000个字符' },
    ],
    ui: {
      order: 11,
      section: 'about',
      placeholder: '简要介绍你的职业背景...',
      helpText: '让雇主快速了解你',
    },
  },
  {
    id: 'key_achievements',
    name: 'keyAchievements',
    label: '主要成就',
    type: 'textarea',
    required: false,
    ui: {
      order: 12,
      section: 'about',
      placeholder: '描述你的主要成就...',
      helpText: '量化你的成就（如：提升效率30%）',
    },
  },
  {
    id: 'availability',
    name: 'availability',
    label: '到岗时间',
    type: 'select',
    required: false,
    options: [
      { value: 'immediate', label: '立即', icon: '⚡' },
      { value: 'two_weeks', label: '2周内', icon: '📅' },
      { value: 'one_month', label: '1个月内', icon: '📆' },
      { value: 'negotiable', label: '可协商', icon: '🤝' },
    ],
    ui: { order: 13, section: 'preferences' },
  },
  {
    id: 'preferred_company_size',
    name: 'preferredCompanySize',
    label: '公司规模偏好',
    type: 'multiselect',
    required: false,
    options: [
      { value: 'startup', label: '初创 (<50人)' },
      { value: 'small', label: '小型 (50-200人)' },
      { value: 'medium', label: '中型 (200-1000人)' },
      { value: 'large', label: '大型 (>1000人)' },
    ],
    ui: { order: 14, section: 'preferences', placeholder: '选择公司规模' },
  },
];

const capabilities: SceneCapability[] = [
  {
    id: 'resume_upload',
    name: '简历上传',
    description: '上传PDF或Word格式简历',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
  },
  {
    id: 'portfolio_link',
    name: '作品集链接',
    description: '链接到GitHub、Behance等',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
  },
  {
    id: 'skill_assessment',
    name: '技能评估',
    description: '在线技能测试和认证',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
  },
  {
    id: 'salary_insights',
    name: '薪资洞察',
    description: '查看市场薪资参考',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
  },
  {
    id: 'company_reviews',
    name: '公司评价',
    description: '查看公司评价和面试经验',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
  },
  {
    id: 'job_alerts',
    name: '职位提醒',
    description: '匹配职位自动推送',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
  },
];

const sections: SceneSection[] = [
  {
    id: 'basic',
    title: '基本信息',
    icon: '📋',
    order: 1,
    fields: ['job_type', 'job_category', 'target_positions', 'expected_salary', 'work_location'],
  },
  {
    id: 'experience',
    title: '经验和技能',
    icon: '🛠️',
    order: 2,
    fields: ['work_experience', 'skills', 'certifications', 'education', 'portfolio_url'],
  },
  {
    id: 'about',
    title: '关于你',
    icon: '👤',
    order: 3,
    fields: ['career_summary', 'key_achievements'],
  },
  {
    id: 'preferences',
    title: '求职偏好',
    icon: '⚙️',
    order: 4,
    fields: ['availability', 'preferred_company_size'],
  },
];

export const agentJobConfig: SceneConfig = {
  id: 'agentjob',
  metadata,
  fields,
  capabilities,
  templates: [
    {
      id: 'software_engineer',
      name: '软件工程师',
      description: '技术岗位求职模板',
      isPreset: true,
      isDefault: false,
      fieldValues: {
        jobCategory: 'tech',
        skills: ['JavaScript', 'React', 'Node.js'],
        jobType: 'full_time',
      },
    },
    {
      id: 'designer',
      name: '设计师',
      description: '设计岗位求职模板',
      isPreset: true,
      isDefault: false,
      fieldValues: {
        jobCategory: 'design',
        skills: ['Figma', 'Adobe XD', 'Photoshop'],
        jobType: 'full_time',
      },
    },
    {
      id: 'product_manager',
      name: '产品经理',
      description: '产品岗位求职模板',
      isPreset: true,
      isDefault: false,
      fieldValues: {
        jobCategory: 'product',
        skills: ['Product Management', 'Agile', 'Data Analysis'],
        jobType: 'full_time',
      },
    },
  ],
  validation: {
    rules: [],
    preventSubmitOnError: true,
    showWarnings: true,
  },
  ui: {
    sections,
    layout: 'tabs',
    theme: {
      primaryColor: '#2196F3',
      secondaryColor: '#BBDEFB',
      backgroundColor: '#E3F2FD',
      textColor: '#333333',
    },
  },
};

export default agentJobConfig;
