import { SceneConfig, SceneMetadata, SceneFieldDefinition, SceneCapability, SceneSection } from '../../types/scene';

const metadata: SceneMetadata = {
  id: 'agentad',
  name: 'Agent广告',
  nameEn: 'AgentAd',
  description: '发布广告、推广产品和服务的场景',
  icon: '📢',
  color: '#FF9800',
  version: '1.0.0',
  isActive: true,
  createdAt: new Date('2026-01-01'),
  updatedAt: new Date('2026-01-01'),
};

const fields: SceneFieldDefinition[] = [
  {
    id: 'ad_type',
    name: 'adType',
    label: '广告类型',
    type: 'select',
    required: true,
    options: [
      { value: 'product', label: '产品推广', icon: '📦' },
      { value: 'service', label: '服务推广', icon: '🛠️' },
      { value: 'event', label: '活动宣传', icon: '🎉' },
      { value: 'brand', label: '品牌宣传', icon: '✨' },
      { value: 'promotion', label: '促销优惠', icon: '🏷️' },
      { value: 'awareness', label: '公益广告', icon: '💚' },
    ],
    ui: { order: 1, section: 'basic' },
  },
  {
    id: 'product_category',
    name: 'productCategory',
    label: '产品/服务类别',
    type: 'select',
    required: true,
    options: [
      { value: 'electronics', label: '电子产品', icon: '📱' },
      { value: 'fashion', label: '服装时尚', icon: '👗' },
      { value: 'food', label: '美食餐饮', icon: '🍔' },
      { value: 'beauty', label: '美妆护肤', icon: '💄' },
      { value: 'home', label: '家居生活', icon: '🏠' },
      { value: 'education', label: '教育培训', icon: '📚' },
      { value: 'travel', label: '旅游出行', icon: '✈️' },
      { value: 'health', label: '健康医疗', icon: '🏥' },
      { value: 'entertainment', label: '娱乐休闲', icon: '🎮' },
      { value: 'business', label: '商务服务', icon: '💼' },
    ],
    ui: { order: 2, section: 'basic' },
  },
  {
    id: 'target_audience',
    name: 'targetAudience',
    label: '目标受众',
    type: 'multiselect',
    required: true,
    options: [
      { value: 'youth', label: '青少年 (13-18)' },
      { value: 'young_adult', label: '年轻人 (18-30)' },
      { value: 'adult', label: '中年人 (30-50)' },
      { value: 'senior', label: '老年人 (50+)' },
      { value: 'family', label: '家庭用户' },
      { value: 'business', label: '企业用户' },
      { value: 'professional', label: '专业人士' },
    ],
    ui: { order: 3, section: 'basic', placeholder: '选择目标受众' },
  },
  {
    id: 'campaign_objective',
    name: 'campaignObjective',
    label: '推广目标',
    type: 'select',
    required: true,
    options: [
      { value: 'awareness', label: '提升知名度', icon: '📢' },
      { value: 'engagement', label: '增加互动', icon: '💬' },
      { value: 'traffic', label: '引流到网站', icon: '🌐' },
      { value: 'leads', label: '获取线索', icon: '👥' },
      { value: 'sales', label: '促进销售', icon: '💰' },
      { value: 'app_install', label: '应用安装', icon: '📲' },
    ],
    ui: { order: 4, section: 'basic' },
  },
  {
    id: 'budget_range',
    name: 'budgetRange',
    label: '预算范围',
    type: 'select',
    required: false,
    options: [
      { value: 'small', label: '小预算 (¥1,000-5,000)' },
      { value: 'medium', label: '中等预算 (¥5,000-20,000)' },
      { value: 'large', label: '大预算 (¥20,000-100,000)' },
      { value: 'enterprise', label: '企业级 (¥100,000+)' },
    ],
    ui: { order: 5, section: 'campaign' },
  },
  {
    id: 'campaign_duration',
    name: 'campaignDuration',
    label: '推广时长',
    type: 'select',
    required: false,
    options: [
      { value: 'short', label: '短期 (1-7天)' },
      { value: 'medium', label: '中期 (1-4周)' },
      { value: 'long', label: '长期 (1-6个月)' },
      { value: 'ongoing', label: '持续投放' },
    ],
    ui: { order: 6, section: 'campaign' },
  },
  {
    id: 'product_name',
    name: 'productName',
    label: '产品/服务名称',
    type: 'text',
    required: true,
    validation: [
      { type: 'maxLength', value: 50, message: '最多50个字符' },
    ],
    ui: { order: 7, section: 'product', placeholder: '输入产品或服务名称' },
  },
  {
    id: 'product_description',
    name: 'productDescription',
    label: '产品/服务描述',
    type: 'textarea',
    required: true,
    validation: [
      { type: 'minLength', value: 30, message: '至少30个字符' },
      { type: 'maxLength', value: 500, message: '最多500个字符' },
    ],
    ui: {
      order: 8,
      section: 'product',
      placeholder: '描述你的产品或服务...',
      helpText: '突出卖点和优势',
    },
  },
  {
    id: 'key_features',
    name: 'keyFeatures',
    label: '主要特点',
    type: 'tags',
    required: false,
    ui: {
      order: 9,
      section: 'product',
      placeholder: '如：免费配送、品质保证',
    },
  },
  {
    id: 'price_info',
    name: 'priceInfo',
    label: '价格信息',
    type: 'text',
    required: false,
    ui: {
      order: 10,
      section: 'product',
      placeholder: '如：¥99起, 限时优惠',
    },
  },
  {
    id: 'promotion_details',
    name: 'promotionDetails',
    label: '促销详情',
    type: 'textarea',
    required: false,
    dependencies: [
      { field: 'adType', operator: 'eq', value: 'promotion' },
    ],
    ui: {
      order: 11,
      section: 'product',
      placeholder: '描述促销活动内容...',
    },
  },
  {
    id: 'website_url',
    name: 'websiteUrl',
    label: '官网链接',
    type: 'url',
    required: false,
    ui: { order: 12, section: 'contact', placeholder: 'https://...' },
  },
  {
    id: 'contact_info',
    name: 'contactInfo',
    label: '联系方式',
    type: 'text',
    required: false,
    ui: {
      order: 13,
      section: 'contact',
      placeholder: '电话或微信号',
    },
  },
  {
    id: 'location',
    name: 'location',
    label: '营业地点',
    type: 'text',
    required: false,
    dependencies: [
      { field: 'adType', operator: 'in', value: ['product', 'service'] },
    ],
    ui: { order: 14, section: 'contact', placeholder: '实体店铺地址' },
  },
  {
    id: 'business_hours',
    name: 'businessHours',
    label: '营业时间',
    type: 'text',
    required: false,
    ui: { order: 15, section: 'contact', placeholder: '如：周一至周日 9:00-21:00' },
  },
];

const capabilities: SceneCapability[] = [
  {
    id: 'image_ads',
    name: '图片广告',
    description: '上传广告图片素材',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    config: {
      maxFileSize: 10 * 1024 * 1024,
      allowedFormats: ['jpg', 'jpeg', 'png', 'gif'],
      recommendedSize: '1200x628',
    },
  },
  {
    id: 'video_ads',
    name: '视频广告',
    description: '上传广告视频素材',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
    config: {
      maxFileSize: 100 * 1024 * 1024,
      allowedFormats: ['mp4', 'mov'],
      maxDuration: 60,
    },
  },
  {
    id: 'audience_targeting',
    name: '受众定向',
    description: '精准定位目标受众',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
  },
  {
    id: 'budget_optimization',
    name: '预算优化',
    description: '智能预算分配建议',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
  },
  {
    id: 'performance_analytics',
    name: '效果分析',
    description: '广告效果数据分析',
    enabled: true,
    version: '1.0.0',
    dependencies: [],
  },
  {
    id: 'a_b_testing',
    name: 'A/B测试',
    description: '多版本广告测试',
    enabled: false,
    version: '0.5.0',
    dependencies: ['performance_analytics'],
  },
];

const sections: SceneSection[] = [
  {
    id: 'basic',
    title: '基本信息',
    icon: '📋',
    order: 1,
    fields: ['ad_type', 'product_category', 'target_audience', 'campaign_objective'],
  },
  {
    id: 'campaign',
    title: '推广计划',
    icon: '📅',
    order: 2,
    fields: ['budget_range', 'campaign_duration'],
  },
  {
    id: 'product',
    title: '产品/服务',
    icon: '📦',
    order: 3,
    fields: ['product_name', 'product_description', 'key_features', 'price_info', 'promotion_details'],
  },
  {
    id: 'contact',
    title: '联系信息',
    icon: '📞',
    order: 4,
    fields: ['website_url', 'contact_info', 'location', 'business_hours'],
  },
];

export const agentAdConfig: SceneConfig = {
  id: 'agentad',
  metadata,
  fields,
  capabilities,
  templates: [
    {
      id: 'product_launch',
      name: '新品发布',
      description: '新产品上市推广模板',
      isPreset: true,
      isDefault: false,
      fieldValues: {
        adType: 'product',
        campaignObjective: 'awareness',
        keyFeatures: ['新品上市', '限时优惠'],
      },
    },
    {
      id: 'discount_sale',
      name: '折扣促销',
      description: '促销活动推广模板',
      isPreset: true,
      isDefault: false,
      fieldValues: {
        adType: 'promotion',
        campaignObjective: 'sales',
        promotionDetails: '限时折扣，先到先得',
      },
    },
    {
      id: 'service_promo',
      name: '服务推广',
      description: '服务类广告模板',
      isPreset: true,
      isDefault: false,
      fieldValues: {
        adType: 'service',
        campaignObjective: 'leads',
      },
    },
    {
      id: 'event_promo',
      name: '活动宣传',
      description: '活动/展会宣传模板',
      isPreset: true,
      isDefault: false,
      fieldValues: {
        adType: 'event',
        campaignObjective: 'engagement',
      },
    },
  ],
  validation: {
    rules: [],
    preventSubmitOnError: true,
    showWarnings: true,
  },
  ui: {
    sections,
    layout: 'tabs',
    theme: {
      primaryColor: '#FF9800',
      secondaryColor: '#FFE0B2',
      backgroundColor: '#FFF3E0',
      textColor: '#333333',
    },
  },
};

export default agentAdConfig;
