import { z } from 'zod';
declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test"]>>;
    PORT: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    API_URL: z.ZodString;
    CLIENT_URL: z.ZodString;
    DATABASE_URL: z.ZodString;
    DB_HOST: z.ZodDefault<z.ZodString>;
    DB_PORT: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    DB_NAME: z.ZodString;
    DB_USER: z.ZodString;
    DB_PASSWORD: z.ZodString;
    REDIS_URL: z.ZodDefault<z.ZodString>;
    REDIS_DB_CACHE: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    REDIS_DB_SOCKET: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    REDIS_DB_QUEUE: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    JWT_SECRET: z.ZodString;
    JWT_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    JWT_REFRESH_SECRET: z.ZodString;
    JWT_REFRESH_EXPIRES_IN: z.ZodDefault<z.ZodString>;
    ANTHROPIC_API_KEY: z.ZodString;
    ANTHROPIC_BASE_URL: z.ZodString;
    ANTHROPIC_MODEL: z.ZodDefault<z.ZodString>;
    S3_ENDPOINT: z.ZodDefault<z.ZodString>;
    S3_PORT: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    S3_USE_SSL: z.ZodDefault<z.ZodEffects<z.ZodString, boolean, string>>;
    S3_ACCESS_KEY: z.ZodString;
    S3_SECRET_KEY: z.ZodString;
    S3_BUCKET_NAME: z.ZodString;
    S3_PUBLIC_URL: z.ZodString;
    BCRYPT_ROUNDS: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    RATE_LIMIT_WINDOW_MS: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    RATE_LIMIT_MAX_REQUESTS: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    CORS_ORIGIN: z.ZodDefault<z.ZodString>;
    ENABLE_AI_FALLBACK: z.ZodDefault<z.ZodEffects<z.ZodString, boolean, string>>;
    ENABLE_REQUEST_LOGGING: z.ZodDefault<z.ZodEffects<z.ZodString, boolean, string>>;
    ENABLE_SWAGGER: z.ZodDefault<z.ZodEffects<z.ZodString, boolean, string>>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["debug", "info", "warn", "error"]>>;
    LOG_PRETTY: z.ZodDefault<z.ZodEffects<z.ZodString, boolean, string>>;
}, "strip", z.ZodTypeAny, {
    LOG_LEVEL: "info" | "error" | "debug" | "warn";
    NODE_ENV: "production" | "development" | "test";
    RATE_LIMIT_MAX_REQUESTS: number;
    DATABASE_URL: string;
    JWT_SECRET: string;
    PORT: number;
    API_URL: string;
    CLIENT_URL: string;
    DB_HOST: string;
    DB_PORT: number;
    DB_NAME: string;
    DB_USER: string;
    DB_PASSWORD: string;
    REDIS_URL: string;
    REDIS_DB_CACHE: number;
    REDIS_DB_SOCKET: number;
    REDIS_DB_QUEUE: number;
    JWT_EXPIRES_IN: string;
    JWT_REFRESH_SECRET: string;
    JWT_REFRESH_EXPIRES_IN: string;
    ANTHROPIC_API_KEY: string;
    ANTHROPIC_BASE_URL: string;
    ANTHROPIC_MODEL: string;
    S3_ENDPOINT: string;
    S3_PORT: number;
    S3_USE_SSL: boolean;
    S3_ACCESS_KEY: string;
    S3_SECRET_KEY: string;
    S3_BUCKET_NAME: string;
    S3_PUBLIC_URL: string;
    BCRYPT_ROUNDS: number;
    RATE_LIMIT_WINDOW_MS: number;
    CORS_ORIGIN: string;
    ENABLE_AI_FALLBACK: boolean;
    ENABLE_REQUEST_LOGGING: boolean;
    ENABLE_SWAGGER: boolean;
    LOG_PRETTY: boolean;
}, {
    DATABASE_URL: string;
    JWT_SECRET: string;
    API_URL: string;
    CLIENT_URL: string;
    DB_NAME: string;
    DB_USER: string;
    DB_PASSWORD: string;
    JWT_REFRESH_SECRET: string;
    ANTHROPIC_API_KEY: string;
    ANTHROPIC_BASE_URL: string;
    S3_ACCESS_KEY: string;
    S3_SECRET_KEY: string;
    S3_BUCKET_NAME: string;
    S3_PUBLIC_URL: string;
    LOG_LEVEL?: "info" | "error" | "debug" | "warn" | undefined;
    NODE_ENV?: "production" | "development" | "test" | undefined;
    RATE_LIMIT_MAX_REQUESTS?: string | undefined;
    PORT?: string | undefined;
    DB_HOST?: string | undefined;
    DB_PORT?: string | undefined;
    REDIS_URL?: string | undefined;
    REDIS_DB_CACHE?: string | undefined;
    REDIS_DB_SOCKET?: string | undefined;
    REDIS_DB_QUEUE?: string | undefined;
    JWT_EXPIRES_IN?: string | undefined;
    JWT_REFRESH_EXPIRES_IN?: string | undefined;
    ANTHROPIC_MODEL?: string | undefined;
    S3_ENDPOINT?: string | undefined;
    S3_PORT?: string | undefined;
    S3_USE_SSL?: string | undefined;
    BCRYPT_ROUNDS?: string | undefined;
    RATE_LIMIT_WINDOW_MS?: string | undefined;
    CORS_ORIGIN?: string | undefined;
    ENABLE_AI_FALLBACK?: string | undefined;
    ENABLE_REQUEST_LOGGING?: string | undefined;
    ENABLE_SWAGGER?: string | undefined;
    LOG_PRETTY?: string | undefined;
}>;
export declare const env: {
    LOG_LEVEL: "info" | "error" | "debug" | "warn";
    NODE_ENV: "production" | "development" | "test";
    RATE_LIMIT_MAX_REQUESTS: number;
    DATABASE_URL: string;
    JWT_SECRET: string;
    PORT: number;
    API_URL: string;
    CLIENT_URL: string;
    DB_HOST: string;
    DB_PORT: number;
    DB_NAME: string;
    DB_USER: string;
    DB_PASSWORD: string;
    REDIS_URL: string;
    REDIS_DB_CACHE: number;
    REDIS_DB_SOCKET: number;
    REDIS_DB_QUEUE: number;
    JWT_EXPIRES_IN: string;
    JWT_REFRESH_SECRET: string;
    JWT_REFRESH_EXPIRES_IN: string;
    ANTHROPIC_API_KEY: string;
    ANTHROPIC_BASE_URL: string;
    ANTHROPIC_MODEL: string;
    S3_ENDPOINT: string;
    S3_PORT: number;
    S3_USE_SSL: boolean;
    S3_ACCESS_KEY: string;
    S3_SECRET_KEY: string;
    S3_BUCKET_NAME: string;
    S3_PUBLIC_URL: string;
    BCRYPT_ROUNDS: number;
    RATE_LIMIT_WINDOW_MS: number;
    CORS_ORIGIN: string;
    ENABLE_AI_FALLBACK: boolean;
    ENABLE_REQUEST_LOGGING: boolean;
    ENABLE_SWAGGER: boolean;
    LOG_PRETTY: boolean;
};
export type Env = z.infer<typeof envSchema>;
export {};
//# sourceMappingURL=env.d.ts.map