"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.agentJobL2Schema = void 0;
const types_1 = require("./types");
/**
 * AgentJob Scene L2 Schema
 * 求职招聘场景 - 用于匹配工作机会或人才
 */
exports.agentJobL2Schema = {
    id: 'agentjob-l2',
    version: '1.0.0',
    scene: 'AGENTJOB',
    title: '求职/招聘偏好',
    description: '设置您的求职或招聘需求',
    fields: [
        {
            id: 'roleType',
            type: types_1.L2FieldType.ENUM,
            label: '角色类型',
            description: '您是求职者还是招聘方',
            required: true,
            options: [
                { value: 'jobseeker', label: '求职者', description: '寻找工作机会' },
                { value: 'employer', label: '招聘方', description: '寻找合适人才' },
                { value: 'both', label: '两者皆是', description: '同时求职和招聘' },
            ],
        },
        {
            id: 'jobType',
            type: types_1.L2FieldType.MULTI_SELECT,
            label: '工作类型',
            description: '您期望的工作类型',
            required: true,
            options: [
                { value: 'fulltime', label: '全职' },
                { value: 'parttime', label: '兼职' },
                { value: 'contract', label: '合同制' },
                { value: 'freelance', label: '自由职业' },
                { value: 'internship', label: '实习' },
                { value: 'remote', label: '远程工作' },
                { value: 'onsite', label: '现场办公' },
                { value: 'hybrid', label: '混合办公' },
            ],
        },
        {
            id: 'industry',
            type: types_1.L2FieldType.MULTI_SELECT,
            label: '行业领域',
            description: '您感兴趣的行业',
            required: true,
            options: [
                { value: 'tech', label: '互联网/科技', icon: '💻' },
                { value: 'finance', label: '金融/投资', icon: '💰' },
                { value: 'education', label: '教育/培训', icon: '📚' },
                { value: 'healthcare', label: '医疗/健康', icon: '🏥' },
                { value: 'retail', label: '零售/电商', icon: '🛒' },
                { value: 'manufacturing', label: '制造业', icon: '🏭' },
                { value: 'media', label: '媒体/广告', icon: '📺' },
                { value: 'consulting', label: '咨询/服务', icon: '💼' },
                { value: 'realestate', label: '房地产', icon: '🏠' },
                { value: 'hospitality', label: '酒店/旅游', icon: '🏨' },
                { value: 'food', label: '餐饮/食品', icon: '🍽️' },
                { value: 'transport', label: '交通/物流', icon: '🚚' },
                { value: 'energy', label: '能源/环保', icon: '⚡' },
                { value: 'nonprofit', label: '非营利/公益', icon: '🤝' },
                { value: 'government', label: '政府/公共', icon: '🏛️' },
            ],
        },
        {
            id: 'experienceLevel',
            type: types_1.L2FieldType.ENUM,
            label: '经验水平',
            description: '您的工作经验水平',
            required: true,
            options: [
                { value: 'entry', label: '应届生/无经验', description: '0-1年经验' },
                { value: 'junior', label: '初级', description: '1-3年经验' },
                { value: 'mid', label: '中级', description: '3-5年经验' },
                { value: 'senior', label: '高级', description: '5-10年经验' },
                { value: 'expert', label: '专家/管理', description: '10年以上经验' },
            ],
        },
        {
            id: 'skills',
            type: types_1.L2FieldType.MULTI_SELECT,
            label: '专业技能',
            description: '您的专业技能（可多选）',
            required: true,
            options: [
                { value: 'programming', label: '编程开发' },
                { value: 'design', label: '设计创意' },
                { value: 'marketing', label: '市场营销' },
                { value: 'sales', label: '销售业务' },
                { value: 'management', label: '管理运营' },
                { value: 'finance', label: '财务分析' },
                { value: 'writing', label: '内容创作' },
                { value: 'communication', label: '沟通协调' },
                { value: 'analysis', label: '数据分析' },
                { value: 'research', label: '研究调研' },
                { value: 'project', label: '项目管理' },
                { value: 'leadership', label: '团队领导' },
                { value: 'languages', label: '外语能力' },
                { value: 'technical', label: '技术专长' },
            ],
        },
        {
            id: 'salaryRange',
            type: types_1.L2FieldType.RANGE,
            label: '薪资范围（千/月）',
            description: '您期望的薪资范围',
            required: false,
            min: 0,
            max: 100,
            step: 1,
            defaultValue: { min: 10, max: 30 },
        },
        {
            id: 'workCulture',
            type: types_1.L2FieldType.MULTI_SELECT,
            label: '企业文化偏好',
            description: '您偏好的企业文化',
            required: false,
            options: [
                { value: 'innovative', label: '创新导向' },
                { value: 'stable', label: '稳定发展' },
                { value: 'fastpaced', label: '快节奏' },
                { value: 'collaborative', label: '协作型' },
                { value: 'independent', label: '独立型' },
                { value: 'result', label: '结果导向' },
                { value: 'learning', label: '学习型' },
                { value: 'diverse', label: '多元包容' },
            ],
        },
        {
            id: 'benefits',
            type: types_1.L2FieldType.MULTI_SELECT,
            label: '期望福利',
            description: '您看重的福利待遇',
            required: false,
            options: [
                { value: 'insurance', label: '五险一金' },
                { value: 'bonus', label: '绩效奖金' },
                { value: 'stock', label: '股权期权' },
                { value: 'pto', label: '带薪年假' },
                { value: 'flexible', label: '弹性工作' },
                { value: 'remote', label: '远程办公' },
                { value: 'training', label: '培训发展' },
                { value: 'meals', label: '工作餐/补贴' },
                { value: 'transport', label: '交通补贴' },
                { value: 'gym', label: '健身福利' },
            ],
        },
        {
            id: 'selfIntroduction',
            type: types_1.L2FieldType.LONG_TEXT,
            label: '自我介绍',
            description: '介绍您的专业背景和优势',
            required: true,
            placeholder: '请描述您的工作经历、专业技能、职业目标等...',
            minLength: 50,
            maxLength: 1000,
        },
        {
            id: 'requirements',
            type: types_1.L2FieldType.LONG_TEXT,
            label: '具体需求',
            description: '描述您对工作的具体要求',
            required: false,
            placeholder: '例如：岗位要求、工作内容、团队氛围等...',
            maxLength: 500,
        },
    ],
    steps: [
        {
            id: 'basic',
            title: '基本信息',
            description: '设置角色和工作类型',
            fields: ['roleType', 'jobType'],
        },
        {
            id: 'industry',
            title: '行业与经验',
            description: '选择行业和经验水平',
            fields: ['industry', 'experienceLevel'],
        },
        {
            id: 'skills',
            title: '技能与薪资',
            description: '填写技能和期望薪资',
            fields: ['skills', 'salaryRange'],
        },
        {
            id: 'preferences',
            title: '偏好设置',
            description: '设置企业文化和福利偏好',
            fields: ['workCulture', 'benefits'],
        },
        {
            id: 'details',
            title: '详细描述',
            description: '详细介绍自己',
            fields: ['selfIntroduction', 'requirements'],
        },
    ],
};
exports.default = exports.agentJobL2Schema;
//# sourceMappingURL=agentJob.js.map