import { L2Schema, L2FieldType } from '../types';

/**
 * AgentAd Scene L2 Schema
 * 广告场景 - 用于发布和匹配广告需求
 */
export const agentAdL2Schema: L2Schema = {
  id: 'agentad-l2',
  version: '1.0.0',
  scene: 'AGENTAD',
  title: '广告需求',
  description: '设置您的广告投放需求或供应',
  fields: [
    {
      id: 'adType',
      type: L2FieldType.ENUM,
      label: '广告类型',
      description: '您是广告需求方还是供应方',
      required: true,
      options: [
        { value: 'advertiser', label: '广告主', description: '需要投放广告' },
        { value: 'publisher', label: '媒体方', description: '提供广告位' },
        { value: 'agency', label: '代理商', description: '广告代理服务' },
        { value: 'creator', label: '创作者', description: '内容创作者接广告' },
      ],
    },
    {
      id: 'adCategory',
      type: L2FieldType.MULTI_SELECT,
      label: '广告类目',
      description: '您感兴趣的广告类型',
      required: true,
      options: [
        { value: 'brand', label: '品牌推广', icon: '📢' },
        { value: 'product', label: '产品推广', icon: '📦' },
        { value: 'app', label: 'App推广', icon: '📱' },
        { value: 'event', label: '活动推广', icon: '🎉' },
        { value: 'content', label: '内容营销', icon: '✍️' },
        { value: 'influencer', label: '网红/KOL', icon: '⭐' },
        { value: 'display', label: '展示广告', icon: '🖼️' },
        { value: 'video', label: '视频广告', icon: '🎬' },
        { value: 'social', label: '社交媒体', icon: '💬' },
        { value: 'search', label: '搜索广告', icon: '🔍' },
        { value: 'native', label: '原生广告', icon: '🌿' },
        { value: 'performance', label: '效果广告', icon: '📊' },
      ],
    },
    {
      id: 'targetAudience',
      type: L2FieldType.MULTI_SELECT,
      label: '目标受众',
      description: '您的目标受众群体',
      required: true,
      options: [
        { value: 'general', label: '大众用户' },
        { value: 'young', label: '年轻人(18-30)' },
        { value: 'middle', label: '中年人(30-50)' },
        { value: 'senior', label: '中老年人(50+)' },
        { value: 'students', label: '学生群体' },
        { value: 'professionals', label: '职场人士' },
        { value: 'parents', label: '家长群体' },
        { value: 'luxury', label: '高端用户' },
        { value: 'tech', label: '科技爱好者' },
        { value: 'fashion', label: '时尚人群' },
        { value: 'health', label: '健康关注者' },
        { value: 'business', label: '商业决策者' },
      ],
    },
    {
      id: 'budgetRange',
      type: L2FieldType.RANGE,
      label: '预算范围（万元）',
      description: '您的广告预算范围',
      required: false,
      min: 0,
      max: 1000,
      step: 1,
      defaultValue: { min: 1, max: 10 },
    },
    {
      id: 'campaignDuration',
      type: L2FieldType.ENUM,
      label: '投放周期',
      description: '期望的投放时长',
      required: true,
      options: [
        { value: 'short', label: '短期(1周内)', description: '快闪活动' },
        { value: 'medium', label: '中期(1-4周)', description: '常规 campaign' },
        { value: 'long', label: '长期(1-3月)', description: '品牌推广' },
        { value: 'ongoing', label: '持续投放', description: '长期合作' },
        { value: 'flexible', label: '灵活安排', description: '根据效果调整' },
      ],
    },
    {
      id: 'adFormat',
      type: L2FieldType.MULTI_SELECT,
      label: '广告形式',
      description: '您需要的广告形式',
      required: true,
      options: [
        { value: 'banner', label: '横幅广告' },
        { value: 'interstitial', label: '插屏广告' },
        { value: 'video', label: '视频广告' },
        { value: 'rewarded', label: '激励视频' },
        { value: 'native', label: '原生广告' },
        { value: 'feed', label: '信息流广告' },
        { value: 'story', label: 'Stories广告' },
        { value: 'search', label: '搜索广告' },
        { value: 'live', label: '直播广告' },
        { value: 'product', label: '商品广告' },
        { value: 'sponsored', label: '赞助内容' },
        { value: 'collab', label: '联名合作' },
      ],
    },
    {
      id: 'kpis',
      type: L2FieldType.MULTI_SELECT,
      label: '目标KPI',
      description: '您的主要投放目标',
      required: true,
      options: [
        { value: 'awareness', label: '品牌曝光', description: '提升知名度' },
        { value: 'engagement', label: '互动参与', description: '增加互动' },
        { value: 'clicks', label: '点击转化', description: '引导点击' },
        { value: 'installs', label: 'App安装', description: '下载安装' },
        { value: 'leads', label: '线索收集', description: '获取潜在客户' },
        { value: 'sales', label: '销售转化', description: '直接销售' },
        { value: 'retention', label: '用户留存', description: '提升留存' },
        { value: 'roi', label: '投资回报率', description: '优化ROI' },
      ],
    },
    {
      id: 'platform',
      type: L2FieldType.MULTI_SELECT,
      label: '投放平台',
      description: '期望的投放渠道',
      required: false,
      options: [
        { value: 'social', label: '社交媒体' },
        { value: 'video', label: '视频平台' },
        { value: 'search', label: '搜索引擎' },
        { value: 'display', label: '展示网络' },
        { value: 'mobile', label: '移动应用' },
        { value: 'ott', label: 'OTT/电视' },
        { value: 'outdoor', label: '户外广告' },
        { value: 'print', label: '印刷媒体' },
        { value: 'radio', label: '广播' },
        { value: 'kol', label: 'KOL合作' },
      ],
    },
    {
      id: 'creativeStyle',
      type: L2FieldType.MULTI_SELECT,
      label: '创意风格',
      description: '偏好的广告创意风格',
      required: false,
      options: [
        { value: 'professional', label: '专业正式' },
        { value: 'casual', label: '轻松随意' },
        { value: 'humorous', label: '幽默风趣' },
        { value: 'emotional', label: '情感共鸣' },
        { value: 'informative', label: '信息丰富' },
        { value: 'minimalist', label: '简约风格' },
        { value: 'vibrant', label: '活力动感' },
        { value: 'luxury', label: '高端奢华' },
      ],
    },
    {
      id: 'timeline',
      type: L2FieldType.DATE,
      label: '期望开始时间',
      description: '希望何时开始投放',
      required: false,
    },
    {
      id: 'adDescription',
      type: L2FieldType.LONG_TEXT,
      label: '广告需求描述',
      description: '详细描述您的广告需求',
      required: true,
      placeholder: '请描述您的品牌/产品、广告目标、预期效果等...',
      minLength: 50,
      maxLength: 1000,
    },
    {
      id: 'requirements',
      type: L2FieldType.LONG_TEXT,
      label: '特殊要求',
      description: '其他特殊要求或限制',
      required: false,
      placeholder: '例如：品牌调性要求、禁投内容、合作方式等...',
      maxLength: 500,
    },
  ],
  steps: [
    {
      id: 'type',
      title: '广告类型',
      description: '选择广告类型和类目',
      fields: ['adType', 'adCategory'],
    },
    {
      id: 'audience',
      title: '受众定位',
      description: '定义目标受众',
      fields: ['targetAudience', 'adFormat'],
    },
    {
      id: 'budget',
      title: '预算与周期',
      description: '设置预算和投放周期',
      fields: ['budgetRange', 'campaignDuration', 'timeline'],
    },
    {
      id: 'goals',
      title: '投放目标',
      description: '选择KPI和投放平台',
      fields: ['kpis', 'platform'],
    },
    {
      id: 'creative',
      title: '创意需求',
      description: '描述创意风格和需求',
      fields: ['creativeStyle', 'adDescription', 'requirements'],
    },
  ],
};

export default agentAdL2Schema;
